version: "3.1"

services:
  AngularCPSS:
    image: node:14.17-alpine
    container_name: AngularCPSS
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 8061:8061
    networks:
      - rete-dev
    entrypoint: ["npm", "start"]

networks:
  rete-dev:
